Exemplify guardians integration with HW provider
multiversx/mx-sdk-js-examples pull request #26
Opened 2023-07-12 17:17 UTC by andreibancioiu

2023-07-13 11:38 UTC, bogdan-rosianu requested changes

2023-07-13 11:38 UTC, bogdan-rosianu commented on signing-providers/src/hw.js
> +            guardian: guardian ? guardian : undefined,
enforce `options` to include the hash signing & guardian (if set)

2023-07-14 07:11 UTC, CiprianDraghici approved these changes

2023-07-14 13:17 UTC, bogdan-rosianu approved these changes

2023-07-17 06:39 UTC, merged